spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/regions
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
  jpa:
    show-sql: true

server:
  port: 5055
